development:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: popcorn_dev
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: popcorn_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: popcorn_production
  pool: 5
